apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "splunk.fullname" . }}-defaults
  labels:
    {{- include "splunk.labels" . | nindent 4 }}
data:
  default.yml: |
    splunk:
      conf:
        web:
          directory: /opt/splunk/etc/system/local
          content:
            settings:
              enable_insecure_legacy_html: {{ .Values.splunk.webConf.enableInsecureLegacyHtml | quote }}
