apiVersion: v1
kind: Service
metadata:
  name: {{ include "splunk.fullname" . }}-hec
  labels:
    {{- include "splunk.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.hec.type }}
  ports:
    - port: {{ .Values.service.hec.port }}
      targetPort: {{ .Values.service.hec.targetPort }}
      protocol: TCP
      name: hec
  selector:
    {{- include "splunk.selectorLabels" . | nindent 4 }}
