{{- if not .Values.clusterIssuer.skipTLSVerify }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.clusterIssuer.name }}-ca-bundle
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cluster-issuer.labels" . | nindent 4 }}
type: Opaque
stringData:
  ca.crt: |
    {{- .Values.ca.crt | nindent 4 }}
{{- end }}
