config:
  clientID: ""
  clientSecret: ""
  cookieSecret: ""  
  redirect_url: "https://auth.kscsc.local/oauth2/callback"
  configFile: |
    provider="entra-id"
    oidc_issuer_url=""
    scope="openid email profile"
    allowed_groups=[""]
    email_domains=["kscsc.online"]    
    cookie_domains=[".kscsc.local"]
    whitelist_domains=["*.kscsc.local"]
    cookie_expire="2h"
  upstreams:
    - "static://200"
ingress:
  enabled: false
  path: /
  hosts:
    - auth.kscsc.local
  tls: []
  proxy_prefix: "/oauth2"
  cookieSecure: false
  extraArgs:
    log-level: "debug"
tolerations:
  - key: "nvidia.com/gpu"
    operator: "Exists"
    effect: "NoSchedule"