{{- if .Values.pvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "scannvnc.pvcName" . }}
  labels:
    app: {{ include "scannvnc.name" . }}
spec:
  accessModes:
{{ toYaml .Values.pvc.accessModes | indent 4 }}
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
{{- if .Values.pvc.storageClass }}
  storageClassName: "{{ .Values.pvc.storageClass }}"
{{- end }}
{{- end }}
