apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: {{ .Release.Name }}-forwarder
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}
      namespace: {{ .Values.gateway.namespace }}
      sectionName: tcp-forwarder
  rules:
    - backendRefs:
        - name: {{ .Values.service.forwarder.serviceName }}
          port: {{ .Values.service.forwarder.targetPort }}
