falco:
  jsonOutput: true
  jsonIncludeOutputProperty: true
  httpOutput:
    enabled: true
    url: "http://falcosidekick:2801/"

falcosidekick:
  enabled: true
  webui:
    enabled: true
    user: "admin:admin" # Default credentials, change in production
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/redirect-entry-point: websecure
      hosts:
        - host: falco.kscsc.local
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
      - secretName: falco-tls
        hosts:
          - falco.kscsc.local

