apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
  labels:
    {{- include "coredns-custom.labels" . | nindent 4 }}
data:
  {{ .Values.zone | replace "." "-" }}.server: |
    {{ .Values.zone }}:53 {
      hosts {
        {{- range .Values.hosts }}
        {{ $.Values.ingressIP }} {{ . }}
        {{- end }}
        fallthrough
      }
      whoami
    }
