
replicaCount: 1

image:
  repository: ollama/ollama
  tag: "0.18.0"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 11434

pvc:
  enabled: true
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  size: 30Gi
  name: ""

model:
  name: SpeakLeash/bielik-11b-v3.0-instruct:Q6_K

commandArgs: []

resources:
  requests:
    cpu: "2"
    memory: "8Gi"
  limits:
    cpu: "4"
    memory: "16Gi"

gpu:
  enabled: true
  resourceName: "nvidia.com/gpu"
  count: 1
  nodeSelector:
  tolerations:
    - key: "nvidia.com/gpu"
      operator: "Exists"
      effect: "NoSchedule"
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
              - key: nvidia.com/gpu.present
                operator: In
                values:
                  - "true"

runtimeClassName: "nvidia"
podSecurityContext: {}
containerSecurityContext: {}

oauth2ProxyBridge:
  enabled: true
  service:
    name: oauth2-proxy
    namespace: oauth2-proxy

ingress:
  enabled: true
  ingressClassName: "nginx"
  annotations: 
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/auth-url: "http://oauth2-proxy.oauth2-proxy.svc.cluster.local/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://auth.kscsc.local/oauth2/start?rd=https://$host$escaped_request_uri"
    nginx.ingress.kubernetes.io/auth-response-headers: "X-Auth-Request-Access-Token,Authorization"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "32k"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
    nginx.ingress.kubernetes.io/client-header-buffer-size: "16k"
    nginx.ingress.kubernetes.io/large-client-header-buffers: "4 16k"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

  hosts:
    - host: ollama.kscsc.local
      paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: ollama-ollama
            servicePort: 11434
  tls:
    - hosts:
      - ollama.kscsc.local
      secretName: ollama-tls

networkPolicy:
  enabled: true
  allow:
    - name: openui
      namespace: openui
    - name: splunk
      namespace: splunk
  ingress:
    enabled: true
    namespace: ingress-nginx
    podLabels:
      app.kubernetes.io/name: ingress-nginx
