{{- if .Values.ui.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: falco-ui
  labels:
    app.kubernetes.io/name: falco-ui
    app.kubernetes.io/instance: {{ .Release.Name }}
automountServiceAccountToken: true
{{- end }}
